#!/bin/bash
OvpnDownload_Port='80' # Before changing this value, please read this document. It contains all unsafe ports for Google Chrome Browser, please read from line #23 to line #89: https://chromium.googlesource.com/chromium/src.git/+/refs/heads/master/net/base/port_util.cc
# Server local time
MyVPS_Time='Asia/Kuala_Lumpur'
#############################
 apt-get update
 apt-get upgrade -y
 apt-get install nginx 
 # Creating nginx config for our ovpn config downloads webserver
 cat <<'myNginxC' > /etc/nginx/conf.d/bonveio-ovpn-config.conf
# My OpenVPN Config Download Directory
server {
 listen 0.0.0.0:myNginx;
 server_name localhost;
 root /var/www/openvpn;
 index index.html;
}
myNginxC

 # Setting our nginx config port for .ovpn download site
 sed -i "s|myNginx|$OvpnDownload_Port|g" /etc/nginx/conf.d/bonveio-ovpn-config.conf
 # Creating our root directory for all of our .ovpn configs
 rm -rf /var/www/openvpn
 mkdir -p /var/www/openvpn
 # rm /var/www/html/index.html
 # rm /var/www/html/index.nginx-debian.html
 wget https://raw.githubusercontent.com/89870must73/DEB/main/index.html
 cp index.html /var/www/html 
 systemctl restart nginx
